# Generated by Django 6.0.6 on 2026-06-18 16:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('category', models.CharField(choices=[('vegetables', 'Овощи и зелень'), ('fruits', 'Фрукты и ягоды'), ('meat', 'Мясо и птица'), ('dairy', 'Молочные продукты'), ('grocery', 'Бакалея и крупы'), ('spices', 'Специи и соусы'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('g', 'г'), ('l', 'л'), ('ml', 'мл'), ('pcs', 'шт'), ('pack', 'уп')], max_length=10, verbose_name='Единица измерения')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу')),
                ('calories', models.IntegerField(default=0, verbose_name='Ккал на 100г')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Белки на 100г')),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Жиры на 100г')),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Углеводы на 100г')),
                ('shelf_life_days', models.IntegerField(default=7, verbose_name='Срок хранения (дней)')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('cooking_time', models.IntegerField(default=30, verbose_name='Время готовки (мин)')),
                ('servings', models.IntegerField(default=2, verbose_name='Количество порций')),
                ('difficulty', models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='easy', max_length=10, verbose_name='Сложность')),
                ('instructions', models.TextField(verbose_name='Пошаговая инструкция')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('purchase_date', models.DateField(auto_now_add=True, verbose_name='Дата покупки')),
                ('expiry_date', models.DateField(verbose_name='Срок годности')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='core.ingredient', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продукт в холодильнике',
                'verbose_name_plural': 'Холодильник',
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Куплено')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='core.ingredient', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пункт списка покупок',
                'verbose_name_plural': 'Список покупок',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], max_length=10, verbose_name='Прием пищи')),
                ('servings_planned', models.IntegerField(default=1, verbose_name='Порций к готовке')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='core.recipe', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Запись в плане питания',
                'verbose_name_plural': 'План питания',
                'ordering': ['date', 'meal_type'],
                'unique_together': {('user', 'date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='core.ingredient', verbose_name='Продукт')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Ингредиент в рецепте',
                'verbose_name_plural': 'Ингредиенты в рецептах',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
